<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 2,
                'child' => 7,
                'grand_id' => 0,
                'store_id' => 13,
                'vender_id' => 6,
                'brand_id' => 3,
                'name' => '{"en":"Canon EOS185"}',
                'des' => '{"en":"<p>The biggest change in the\\u00a0<strong>Canon EOS 1500D<\\/strong>\\u00a0is the sensor resolution. It\'s now a 24.1-megapixel APS-C sensor, compared to the 18-megapixel APS-C sensor on the 1300D. ... Just like the 1300D, the\\u00a0<strong>EOS 1500D<\\/strong>\\u00a0features NFC and Wi-Fi for connecting it to your smartphone<\\/p>"}',
                'tags' => '{"en":"camera,canon,lens,eos,1500d,photo,capture"}',
                'model' => 'eos1500d',
                'sku' => 'DEMOSKU',
                'price_in' => 'USD',
                'price' => 324.36,
                'offer_price' => '0',
                'featured' => '1',
                'status' => '1',
                'tax' => 2,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
            'key_features' => '{"en":"<ul>\\r\\n<li>24.1MP APS-C CMOS sensor &amp; DIGIC 4+ image processor.<\\/li>\\r\\n<li>9-point AF with 1 centre cross-type AF point.<\\/li>\\r\\n<li>Standard ISO 100 - 6400 (expandable to 12800)<\\/li>\\r\\n<li>Wi-Fi \\/ NFC supported.<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '9',
                'w_my' => 'month',
                'w_type' => 'Warranty',
                'vender_price' => 318.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '6.36',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-15 18:03:50',
                'updated_at' => '2020-08-08 11:56:05',
                'tax_r' => NULL,
                'tax_name' => '{"en":null}',
                'deleted_at' => NULL,
                'video_preview' => NULL,
                'video_thumbnail' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 2,
                'child' => 7,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 2,
                'name' => '{"en":"Mini Instant Camera"}',
                'des' => '{"en":"<p>Shake up your life with the Fujifilm instax mini 9 - a compact instant camera with a cute and iconic design. Including a selfie mirror and close-up lens, this camera captures perfect selfie photos every time. Brand new features, like the high-key mode for brighter photos and the automatic exposure measurement for aperture settings, enables you to obtain on-the-spot credit-card size photos instantly. This trendy instax mini 9 ice blue camera is super easy to use, and compatible with instax mini film. From holidays to anniversaries, birthdays to valentines there always seems an upcoming event requiring a personalized gift. Instax mini9 instant camera is a perfect gift for your kids to explore photography as a hobby and your perfect accessory for making all the DIY gifts and capturing one-off moments at parties, festivals,vacations,birthdays,wedding, and fun days out.<\\/p>"}',
                'tags' => '{"en":"mini camera,camera,instant camera"}',
                'model' => 'Mini9',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 389.0,
                'offer_price' => '0',
                'featured' => '1',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 0,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => '2021-03-29 14:40:33',
            'key_features' => '{"en":"<ul>\\r\\n<li>New Selfie Mirror and close-up lense attachment for perfect selfies; Produces instant credit card size photos ; Focusing: 0.6m - \\u221e ; Auto power off time: 5 min ; Power Supply: Two AA-size 1.5V alkaline batteries Capacity: 100 shots(Approximately 10 instax mini film packs with new AA batteries) ; Film Feeding out: Automatic<\\/li>\\r\\n<li>Built-in Flash and Automatic exposure Measurement: The camera signals the recommended aperture setting with a flashing LED. This helps capture the perfect photo every time<\\/li>\\r\\n<li>High-Key mode : Take brighter pictures with a soft look - perfect for portraits; Viewfinder-Real image finder, 0.37x, with target spot<\\/li>\\r\\n<li>Uses Instax Mini Film, print size 54 (w) x 86 (H)mm, image size 46 (w) x 62 (H)mm<\\/li>\\r\\n<li>instax mini 9 camera - Smoky white instant camera, Hand Strap, Close-up Lens Attachment, AA Batteries x2, Instruction Manual and 1 year manufacturer warranty for camera<\\/li>\\r\\n<li>New Selfie Mirror and close-up lense attachment for perfect selfies; Produces instant credit card size photos<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '1',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 389.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 15:25:16',
                'updated_at' => '2020-11-24 14:40:40',
                'tax_r' => '18',
                'tax_name' => '{"en":"TAX"}',
                'deleted_at' => NULL,
                'video_preview' => '',
                'video_thumbnail' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 2,
                'child' => 7,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 3,
                'name' => '{"en":"Canon IXUS 185"}',
                'des' => '{"en":"<p>The 8x optical zoom with a 20.0-megapixel and a DIGIC 4+ image processor makes capturing sharp and high resolution images in a breeze. Plus, with the digital IS, shooting of images are almost shake-free even at high zoom lengths to get clear and vivid quality. In addition to the camera advance\'s technology detects optimal settings and boasts ease in operation to simply point and shoot.<\\/p>"}',
                'tags' => '{"en":"canon,camera,IXUS 185"}',
                'model' => 'IXUS185',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 661.98,
                'offer_price' => '0',
                'featured' => '1',
                'status' => '1',
                'tax' => 2,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '1',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
            'key_features' => '{"en":"<ul>\\r\\n<li>20.0 megapixels<\\/li>\\r\\n<li>8x optical zoom (28 - 224)<\\/li>\\r\\n<li>16x ZoomPlus<\\/li>\\r\\n<li>Easy mode and date stamp feature<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '10',
                'w_my' => 'month',
                'w_type' => 'Warranty',
                'vender_price' => 649.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '12.98',
                'shipping_id' => NULL,
                'return_policy' => 1,
                'created_at' => '2020-01-16 15:40:29',
                'updated_at' => '2020-07-10 10:13:45',
                'tax_r' => NULL,
                'tax_name' => '{"en":null}',
                'deleted_at' => NULL,
                'video_preview' => NULL,
                'video_thumbnail' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 2,
                'child' => 8,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 1,
                'name' => '{"en":"Apple iPad Pro"}',
                'des' => '{"en":"<p>The Apple iPad Pro is a 12.9-<strong>inch<\\/strong>\\u00a0touch screen tablet PC that is larger and offers higher resolution than Apple\'s other iPad models. The iPad Pro was scheduled to debut in November 2015, running the iOS 9 operating system.<\\/p>"}',
                'tags' => '{"en":"ipad pro,apple,ipad"}',
                'model' => 'iPad11',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 702.78,
                'offer_price' => '0',
                'featured' => '1',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '1',
                'cancel_avl' => 1,
                'selling_start_at' => '2020-04-25 16:49:35',
                'key_features' => '{"en":"<ul>\\r\\n<li>11-inch edge-to-edge Liquid Retina display with ProMotion, True Tone, and wide color<\\/li>\\r\\n<li>A12X Bionic chip with Neural Engine<\\/li>\\r\\n<li>Face ID for secure authentication<\\/li>\\r\\n<li>12-megapixel back camera, 7-megapixel TrueDepth front camera<\\/li>\\r\\n<li>Four speaker audio with wider stereo sound<\\/li>\\r\\n<li>802.11ac Wi-Fi<\\/li>\\r\\n<li>Up to 10 hours of battery life<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 689.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '13.78',
                'shipping_id' => NULL,
                'return_policy' => 1,
                'created_at' => '2020-01-16 15:58:10',
                'updated_at' => '2020-07-10 10:28:36',
                'tax_r' => '2',
                'tax_name' => '{"en":"ELECTRONICTAX"}',
                'deleted_at' => NULL,
                'video_preview' => NULL,
                'video_thumbnail' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 2,
                'child' => 8,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 2,
                'brand_id' => 1,
                'name' => '{"en":"Apple iPad Air"}',
                'des' => '{"en":"<p>The\\u00a0<strong>iPad Air is the<\\/strong>\\u00a0first-generation\\u00a0<strong>iPad Air<\\/strong>\\u00a0tablet computer designed, developed, and marketed by\\u00a0<strong>Apple<\\/strong>\\u00a0Inc. ... The\\u00a0<strong>iPad Air<\\/strong>\\u00a0features a thinner design with similarities to the contemporaneous\\u00a0<strong>iPad Mini<\\/strong>\\u00a02 with the same 64-bit\\u00a0<strong>Apple<\\/strong>\\u00a0A7 processor with M7 coprocessor.<\\/p>"}',
                'tags' => '{"en":"apple ,ipad air, ipad"}',
                'model' => 'iPadAir',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 459.0,
                'offer_price' => '436.56',
                'featured' => '0',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>10.5-inch Retina display with True Tone and wide color<\\/li>\\r\\n<li>A12 Bionic chip<\\/li>\\r\\n<li>Touch ID fingerprint sensor and Apple Pay<\\/li>\\r\\n<li>8MP back camera, 7MP FaceTime HD front camera<\\/li>\\r\\n<li>Stereo speakers<\\/li>\\r\\n<li>802.11ac Wi-Fi and Gigabit-class LTE cellular data<\\/li>\\r\\n<li>Up to 10 hours of battery life<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 450.0,
                'vender_offer_price' => 428.0,
                'commission_rate' => '8.56',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 16:34:42',
                'updated_at' => '2020-07-10 10:28:45',
                'tax_r' => '2',
                'tax_name' => '{"en":"ELECTRONICTAX"}',
                'deleted_at' => NULL,
                'video_preview' => NULL,
                'video_thumbnail' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 2,
                'child' => 8,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 1,
                'name' => '{"en":"Apple iPad Mini"}',
            'des' => '{"en":"<p>The beloved 7.9-inch iPad mini is more capable than ever.It features the A12 Bionic chip with Neural Engine, which uses real-time machine learning to transform the way you experience photos, gaming, augmented reality (AR), and more. A beautiful Retina display with True Tone for easier viewing in all kinds of lighting environments. Support for Apple Pencil. Wi-Fi and Gigabit-class LTE. An 8MP back camera and 7MP FaceTime HD camera. As well as all-day battery life, Touch ID and Apple Pay, and over a million iPad apps on the App Store\\u2014in an iPad that fits in one hand.<\\/p>"}',
                'tags' => '{"en":"ipad,apple,ipad mini"}',
                'model' => 'iPadAir',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 366.18,
                'offer_price' => '0',
                'featured' => '0',
                'status' => '1',
                'tax' => 2,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '1',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>7.9-inch Retina display with True Tone and wide color<\\/li>\\r\\n<li>A12 Bionic chip<\\/li>\\r\\n<li>Touch ID fingerprint sensor<\\/li>\\r\\n<li>8MP back camera, 7MP FaceTime HD front camera<\\/li>\\r\\n<li>Stereo speakers<\\/li>\\r\\n<li>802.11ac Wi-Fi with Gigabit-class LTE cellular data<\\/li>\\r\\n<li>Up to 10 hours of battery life<\\/li>\\r\\n<li>Lightning connector for charging and accessories<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '1',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 359.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '7.18',
                'shipping_id' => NULL,
                'return_policy' => 1,
                'created_at' => '2020-01-16 16:48:34',
                'updated_at' => '2020-07-10 10:28:51',
                'tax_r' => NULL,
                'tax_name' => '{"en":null}',
                'deleted_at' => NULL,
                'video_preview' => NULL,
                'video_thumbnail' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 4,
                'child' => 10,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 1,
                'name' => '{"en":"HYBRID SMARTWATCH CARLIE"}',
                'des' => '{"en":"<p>1x Fossil Carlie Hybrid Rose Gold Smartwatch FTW5060<\\/p>"}',
                'tags' => '{"en":"fossil ,watch,analog ,carlie ,hybrid ,women\'s watches"}',
                'model' => 'WTCHBD',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 100.0,
                'offer_price' => '50',
                'featured' => '1',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>Dial Color: White, Case Shape: Round, Dial Glass Material: Mineral<\\/li>\\r\\n<li>Band Color: Gold, Band Material: Stainless Steel<\\/li>\\r\\n<li>Watch Movement Type: Quartz, Watch Display Type: Analog<\\/li>\\r\\n<li>Case Material: Stainless Steel, Case Diameter: 36 millimeters, Stainless Steel Bezel<\\/li>\\r\\n<li>Water Resistance Depth: 30 meters, Deployment Buckle Clasp<\\/li>\\r\\n<li>hybrid<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '1',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 100.0,
                'vender_offer_price' => 50.0,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 16:57:08',
                'updated_at' => '2020-11-24 14:33:43',
                'tax_r' => '18',
                'tax_name' => '{"en":"ELECTRONICTAX"}',
                'deleted_at' => NULL,
                'video_preview' => '',
                'video_thumbnail' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 1,
                'child' => 3,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 4,
                'name' => '{"en":"2 Seater Sofa"}',
                'des' => '{"en":"<p>Curl up in this 2 seater sofa\'s padded shape and high, scooped arms. Silver Grey upholstery gives Haring a calming feel, and piping gives this affordable design high-end credentials. Our favourite place to unwind.<\\/p>"}',
                'tags' => '{"en":"laptop,hewelet packard,HP Pavillion"}',
                'model' => 'SOFA123',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 840.0,
                'offer_price' => '0',
                'featured' => '0',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>Curl-up calm<\\/li>\\r\\n<li>padded shape and high<\\/li>\\r\\n<li>Silver Grey upholstery<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 840.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 17:08:08',
                'updated_at' => '2020-11-24 14:27:44',
                'tax_r' => '18',
                'tax_name' => '{"en":"GST"}',
                'deleted_at' => NULL,
                'video_preview' => '',
                'video_thumbnail' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 3,
                'child' => 4,
                'grand_id' => 3,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 1,
                'name' => '{"en":"Frok"}',
                'des' => '{"en":"<p>Get the perfect princess look for your little daughter in this party wear frock made from soft tissue fabric that is skin-friendly for your little one.<\\/p>\\r\\n<p>Kid\'s clothing always symbolizes with cute colors, and this party dress from Wish Karo will not disappoint you. It comes in Four different types of lovely colors.<\\/p>\\r\\n<p>This sleeveless fluffy dress is ideal for any birthday parties, wedding receptions or family functions.<\\/p>"}',
                'tags' => '{"en":"laptop,lenovo,lenovo legion"}',
                'model' => 'LEGION',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 15.0,
                'offer_price' => '10',
                'featured' => '1',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>Fabric: Soft premium quality Net, with cotton lining for utmost comfort<\\/li>\\r\\n<li>Sleeve type: Short Sleevs<\\/li>\\r\\n<li>Ideal for all party occasions, birthday, festives and gifting<\\/li>\\r\\n<li>Wash Care: Hand wash in cold water with mild detergent, do not tumble dry<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 15.0,
                'vender_offer_price' => 10.0,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 17:16:00',
                'updated_at' => '2020-11-24 12:52:41',
                'tax_r' => '2',
                'tax_name' => '{"en":"TAX"}',
                'deleted_at' => NULL,
                'video_preview' => '',
                'video_thumbnail' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 2,
                'child' => 9,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 3,
                'name' => '{"en":"Lenovo Yoga"}',
            'des' => '{"en":"<p>Gorgeous video. Enhanced, immersive audio. It\\u2019s all here in the Yoga 520, a stylish 14\\u201d 2-in-1 laptop with a powerful processor and long-lasting battery life. Chic, flexible, creative. Just like you. Work from home, or pop it in your bag on a day out. Starting at 1.74 kg, the Yoga 520 will easily go wherever life takes you. Finished in sleek aluminium, the Yoga 520 is available in Mineral Grey, Onyx Black, and Metallic Gold. Its precision-cut bevelled edges were designed for a clean and modern look, and an updated touchpad provides smooth comfort and improved control.. More than just a traditional laptop, the Yoga 520 transitions with your schedule. Thanks to a durable 360-degree hinge, you can easily flip into tablet mode for browsing the web, or stream a TV show in tent mode. With this much flexibility, you\\u2019ll always find your perfect viewing angle. Yoga 520 brings you Windows 10 Home, built with a host of new features to streamline your life. Meet Cortana, your own personal digital assistant who answers your questions, sets reminders and learns what you like the more you use it. Cortana works with more than a thousand apps to ensure you\\u2019ll always have the answers you need. Best of all, Cortana syncs across all your Windows 10 devices to keep you organized. 10.4 hours of battery life means you\\u2019ll never feel anchored to an outlet. Plus, the Yoga 520 comes with an always-on USB 3.0 port, which means you\\u2019ll be able to charge your other favourite devices even when your laptop is powered off.. With up to a Full HD (14\\u201d) IPS touch screen display, you\\u2019ll be able to watch movies and browse the web in vivid detail from nearly every angle - whether you\\u2019re lounging on the couch, or watching with a friend. And we\\u2019ve narrowed the bezels on two sides of the screen to maximize your viewing experience.. Immerse yourself in your favourite album, or stay tuned during a conference call, on Harman Speakers with Dolby\\u00ae Audio Premium\\u2122. Featuring an advanced volume maximize, the Yoga 520 delivers louder, clearer sound quality without digital distortion or pumping - and a sound leveller ensures that your audio will remain consistent no matter what program you\\u2019re using.<\\/p>"}',
                'tags' => '{"en":"lenovo,thinkpad,ypga,laptop"}',
                'model' => 'THINKPADYOGA',
                'sku' => 'DEMOSKU',
                'price_in' => 'INR',
                'price' => 410.0,
                'offer_price' => '0',
                'featured' => '0',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
            'key_features' => '{"en":"<ul>\\r\\n<li>Processor: 8th Gen Intel Core i3-8130U processor, 2.2GHz base speed processor<\\/li>\\r\\n<li>Operating System: Pre-loaded Windows 10 Home with lifetime validity<\\/li>\\r\\n<li>Display: 14-inch FHD (1920x1080) display | Touchscreen enabled | Anti Glare<\\/li>\\r\\n<li>Memory and Storage: 4GB DDR4 RAM with Integrated graphics | Storage: 1TB HDD<\\/li>\\r\\n<li>Design and battery: Touchscreen convertible laptop |Thin and light design | Laptop weight 1.7kg | Lithium battery<\\/li>\\r\\n<li>Warranty: This genuine Lenovo laptop comes with 1 year domestic warranty from Lenovo covering manufacturing defects and not covering physical damage. For more details, see Warranty section below<\\/li>\\r\\n<li>Pre-installed Software: Windows 10 Home| In the Box: Laptop with included active pen, battery and charger<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 410.0,
                'vender_offer_price' => NULL,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-01-16 17:26:03',
                'updated_at' => '2020-11-24 15:22:51',
                'tax_r' => '8',
                'tax_name' => '{"en":"GST"}',
                'deleted_at' => NULL,
                'video_preview' => '',
                'video_thumbnail' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'child' => 8,
                'grand_id' => 0,
                'store_id' => 1,
                'vender_id' => 1,
                'brand_id' => 2,
                'name' => '{"en":"iPad"}',
                'des' => '{"en":"<p>The iPad Pro is a 12.9-<strong>inch<\\/strong>\\u00a0touch screen tablet PC that is larger and offers higher resolution than Apple\'s other iPad models. The iPad Pro was scheduled to debut in November 2015, running the iOS 9 operating system.<\\/p>"}',
                'tags' => '{"en":"ipad,ipadpro,ipads,"}',
                'model' => 'TESTIPADX123',
                'sku' => NULL,
                'price_in' => 'INR',
                'price' => 200.0,
                'offer_price' => '180',
                'featured' => '1',
                'status' => '1',
                'tax' => 0,
                'codcheck' => 1,
                'free_shipping' => 1,
                'return_avbl' => '0',
                'cancel_avl' => 1,
                'selling_start_at' => NULL,
                'key_features' => '{"en":"<ul>\\r\\n<li>11-inch edge-to-edge Liquid Retina display with ProMotion, True Tone, and wide color<\\/li>\\r\\n<li>A12X Bionic chip with Neural Engine<\\/li>\\r\\n<li>Face ID for secure authentication<\\/li>\\r\\n<li>12-megapixel back camera, 7-megapixel TrueDepth front camera<\\/li>\\r\\n<li>Four speaker audio with wider stereo sound<\\/li>\\r\\n<li>802.11ac Wi-Fi<\\/li>\\r\\n<li>Up to 10 hours of battery life<\\/li>\\r\\n<\\/ul>"}',
                'w_d' => '2',
                'w_my' => 'year',
                'w_type' => 'Warranty',
                'vender_price' => 200.0,
                'vender_offer_price' => 180.0,
                'commission_rate' => '0',
                'shipping_id' => NULL,
                'return_policy' => 0,
                'created_at' => '2020-11-24 11:36:25',
                'updated_at' => '2020-11-24 11:36:25',
                'tax_r' => '5',
                'tax_name' => '{"en":"TAX NAME"}',
                'deleted_at' => NULL,
                'video_preview' => '<iframe width="420" height="315" src="//www.youtube.com/embed/bXHfrdi_fsU" frameborder="0" allowfullscreen></iframe>',
                'video_thumbnail' => 'video_thumbnail_5fbca2deddc30.webp',
            ),
        ));
        
        
    }
}